# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn run build --if-present
    - run: yarn test
    - name: Deploy application to Heroku QA
      if: github.ref == 'refs/heads/develop'
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
          heroku_api_key: ${{secrets.HEROKU_API_SECRET}}
          heroku_app_name: "finance-web-qa"
          heroku_email: "matheuszanotoesteves@gmail.com"
          healthcheck: "https://finance-web-qa.herokuapp.com/healthcheck"
          delay: 120
          rollbackonhealthcheckfailed: true
    - name: Deploy application to Heroku Production
      if: github.ref == 'refs/heads/main'
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
          heroku_api_key: ${{secrets.HEROKU_API_SECRET}}
          heroku_app_name: "stonks-web-prod"
          heroku_email: "matheuszanotoesteves@gmail.com"
          healthcheck: "https://stonks-web-prod.herokuapp.com/healthcheck"
          delay: 120
          rollbackonhealthcheckfailed: true